# Generated by Django 3.0 on 2020-05-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
    ]
