# Generated by Django 3.0 on 2020-05-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
    ]
